# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    pdf_directory: '%kernel.project_dir%/public/uploads/pdfs'
    temp_directory: '%kernel.project_dir%/var/tmp'



# config/services.yaml

services:
    # Autres configurations de service...

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Scheduler\VerifEcheance:
        tags: [scheduler.provider]
